### ISSUE TITLE
Invalid UlAccessibilityTraits "tablist'

### ISSUE THREAD

**Issue by francois-pasquier** [NativeVision/viro#116]
# Requirements: 
Please go through this checklist before opening a new issue
  - [x] Review the [documentation](https://docs.viromedia.com/)
  - [x] Search for existing issues in: [viromedia/viro](https://github.com/viromedia/viro/issues) & [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [x] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iOS 15.3.1
4. Device(s): iPhone SE 2020

## Description
When starting the app I am getting this error:
```
Invalid UlAccessibilityTraits "tablist'., should
be one of: (
adjustable,
allowsDirectInteraction,
button,
disabled,
frequentUpdates,
header,
image,
key,
link,
none,
pageTurn,
plays,
search,
selected,
startsMedia,
summary,
text
)
RCTConvertEnumValue
```

![IMG_DDE6CF343233-1](https://user-images.githubusercontent.com/19970734/160461055-f27b4ac1-1dd0-4bf4-be83-f82ffad80684.jpeg)

It happens on 2.23.0 and 2.22.0

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

**Comment by robertjcolley** [comment]
Can you provide a reproducible demo? maybe fork the starter kit and share with us here so I can look into it more?

**Comment by francois-pasquier** [comment]
So this was due to using `@react-navigation/bottom-tabs`.

I fixed this by using `patch-packages` and I patched bottom-tabs to replace `tablist` to `button` as pointed out by an issue on stackoverflow.

Again, I wonder if the issue should be closed as what I did to fix it shouldn't needed.

Please note this doesn't happen on Android, only in iOS from what I remember.

**Comment by bigxalx** [comment]
Could you please explain in more detail, or point me in the direction of how exactly you fixed this? 
I've tried your suggested fix by changing `tablist` to `button` in `node_modules/@react-navigation/bottom-tabs/src/views/BottomTabBar.tsx`. I can't find any other occurances of `tablist`, but still I get the same error. 
![IMG_4E30E84F558B-1](https://user-images.githubusercontent.com/511330/167490102-7657b5ad-9cfc-4c08-a733-7862203c18b9.jpeg)

**Comment by Sunil-prajapati** [comment]
please follow this link 
it will work 100%
[https://stackoverflow.com/questions/71119108/invalid-uiaccessibilitys-tablist-error-after-installing-react-native-vector-ic](url)

**Comment by darringrove** [comment]
I confirmed that this error exists after adding react-viro. This work around did resolve the issue temporarily, but what is the root cause and permanent solution?
