### ISSUE TITLE
How to translate the position value according to the device gyroscope data?

### ISSUE THREAD

**Issue by Robiullah2244** [NativeVision/viro#127]
# Requirements: 
Please go through this checklist before opening a new issue
  - [x] Review the [documentation](https://docs.viromedia.com/)
  - [x] Search for existing issues in: [viromedia/viro](https://github.com/viromedia/viro/issues) & [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [x] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iOS version (12.5)
3. Version: React Native version 
4. Device(s):  iPhone 12

## Description
I want to translate the position value according to the device gyroscope data.

**Comment by sanoopks** [comment]
Could you please give more information ? 
If you are asking about camera rotation based on gyroscope, this solution will help you.
[https://github.com/viromedia/viro/issues/543#issuecomment-1340973014](url)
