### ISSUE TITLE
Is it planned to support RN version 0.66.1?

### ISSUE THREAD

**Issue by illi-homz** [NativeVision/viro#133]
If you plan to upgrade, when can we expect it?

I am trying to install the library with the command
`npm i @viro-community/react-viro`

but i get an error
```
npm ERR! While resolving: zvet@0.0.1
npm ERR! Found: react-native@0.66.1
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.66.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"0.65.1" from @viro-community/react-viro@2.23.0
npm ERR! node_modules/@viro-community/react-viro
npm ERR!   @viro-community/react-viro@"*" from the root project
```

if forced to install with parameter (--force), the application always crashes

### difference in config
android/build.gradle:
```
...
classpath("com.android.tools.build:gradle:4.2.2")
...
```

android/gradle/wrapper/gradle-wrapper.properties:
```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip
...
```

**Comment by illi-homz** [comment]
> я пытаюсь установать библиотеку
> 
> `npm i @viro-community/react-viro`
> 
> но получаю ошибку:
> 
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: zvet@0.0.1
> npm ERR! Found: react-native@0.66.1
> npm ERR! node_modules/react-native
> npm ERR!   react-native@"0.66.1" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react-native@"0.65.1" from @viro-community/react-viro@2.23.0
> npm ERR! node_modules/@viro-community/react-viro
> npm ERR!   @viro-community/react-viro@"*" from the root project
> ```
> 
> если установить принулительно c `--force`
> 
> android/build.gradle buildscript{ ext{ ... minSdkVersion = 24 ... } ... dependencies{ classpath('com.android.tools.build:gradle:4.2.2') <- not 4.1.1 } }
> 
> android/gradle/wrapper/gradle-wrapper.properties

**Comment by robertjcolley** [comment]
Hi @illi-homz, with the release of 2.23.1, we now support more versions of React Native!
