### ISSUE TITLE
Record video from the back camera while viewing a scene

### ISSUE THREAD

**Issue by corbt** [NativeVision/viro#175]
Hey everyone,

Is it possible to record the video from the back camera of the device while displaying a scene? I have found the [startVideoRecording](https://viro-community.readme.io/docs/viroarscenenavigator#startvideorecordingfilename-string-savetocameraroll-bool-onerror-func) callback, but the documentation says it "[captures] only Viro-rendered components and external audio".

Our use case is that we'd like to show some guides in AR that demonstrate the camera path a user should follow, and then record their video while they follow that path so we can later use that video to reconstruct their environment. Thanks!

**Comment by sarimahmad** [comment]
@corbt did you find any solution ?

**Comment by corbt** [comment]
No, we ended up not being able to use AR for this.

**Comment by robertjcolley** [comment]
Please fill in the development information in the issue template. We want your projects you build with NativeVision to be successful! However, we are a small team, and we don't have the time to spend trying to figure out what configuration of React Native / iOS / Android / Expo / NativeVision / Windows / MacOS / Linux you are using.

We have a few issues like #228 that we are tracking with more information provided about the recording not working.

I'll happily reopen with the template filled out! 😊
