### ISSUE TITLE
Doesn't run on expo

### ISSUE THREAD

**Issue by ls30378** [NativeVision/viro#177]
# Requirements: 
Please go through this checklist before opening a new issue
  - [x] Review the [documentation](https://docs.viromedia.com/)
  - [x] Search for existing issues in: [viromedia/viro](https://github.com/viromedia/viro/issues) & [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [x] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment
Please provide the following information about your environment:
1. Development OS: Mac, Windows, Linux
- Linux
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on?
- Android Emulator - Pixel 5 Android Version 13
3. Version: ViroReact version and React Native version 
-     "react-native": "0.70.5",     "@viro-community/react-viro": "^2.23.0",
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)
- On Android Emulator

## Description
I created new expo-cli project to learn ViroAR but I can't start the project, after I installed the package I added it to app.json and prebuild the project, after that I builded with eas, installed the development build in emulator and now when I try to open the app it just shows the splash screen and after that it crashes. I didn't implement anything in any js file, is just the file that comes when you create new expo project

## Reproducible Demo
```
"expo": {
    "plugins": [
      "@viro-community/react-viro"
    ],
```

**Comment by adnandothussain** [comment]
Not able to run on react-native": "0.70.6

**Comment by ls30378** [comment]
> Not able to run on react-native": "0.70.6

Any solution?

**Comment by adnandothussain** [comment]
> > Not able to run on react-native": "0.70.6
> 
> Any solution?

Not yet, I guess they are not supporting the latest react native version above than 0.69. I'm not able to run it on android and ios as well

**Comment by robertjcolley** [comment]
We support [Expo Dev Clients](https://viro-community.readme.io/docs/integrating-with-expo) and `npx expo prebuild`. We support the most recent 4 SDKs of Expo (47, 48, 49, 50).

I've updated 2.23.1 to support more versions of React Native as well. If there are other issues you are running into, please open a new issue! 😄
