### ISSUE TITLE
Apparently deadcode log with the following content "'RESOURCES', undefined" freezes app

### ISSUE THREAD

**Issue by ViktorVojtek** [NativeVision/viro#181]
## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iOS version (15.7) is your device running on?
3. Version: ViroReact 2.23 and React Native version 0.67.2
4. Device(s): iPhone 7

## Description
After adding ViroNode with 3DOBjecto to the scene, viro starts logging the following console.log('RESOURCES', undefined);
This logging freeze application after couple of seconds. Dragging of object feels terrible laggy.

I don't know if it is related but onRotate event wont fire at all.

No such issues on viro v 2.22.0

**Comment by dragoshuniq** [comment]
Same here, I have this problem for `Viro3DObject`

**Comment by ShaakhDev** [comment]
I have faced the same issue with `Viro3DObject`

**Comment by robertjcolley** [comment]
Fixed in https://github.com/NativeVision/viro/commit/d0ded8d1e901a98e4452a23a4b0b235559d80ff1. Please try 2.23.1! 😄

**Comment by ShaakhDev** [comment]
Yes, it worked after I updated. Thank you so much.
