### ISSUE TITLE
Unable to take the screenshot.

### ISSUE THREAD

**Issue by haidernawaz99** [NativeVision/viro#184]
Hi,I am trying to take a screenshot but i am getting the following error.

```
onButtonTap = async () => {
if (!this.state.writeAccessPermission) {
this.requestWriteAccessPermission();
}
try {
await this.ARSceneNav.sceneNavigator.takeScreenshot('kartvya', true).then(result => {
console.log(result.url, 'urlurlurlurlurl');
console.log(result.success, 'successsuccesssuccesssuccesssuccess');
console.log(result.errorCode, 'errorCodeerrorCodeerrorCodeerrorCode');
});
} catch (error) {
console.log(error, 'errorerrorerrorerrorerror');
}
};

<TouchableOpacity
style={{justifyContent: 'center'}}
onPress={this.onButtonTap}>
Capture
```

**It throws an error: 
_Arguments appears to not be a React Component. Keys: push,pop,popN,jump,replace,startVideoRecording,stopVideoRecording,takeScreenshot,resetARSession,setWorldOrigin,project,unproject,viroAppProps_**

![195499910-137a3ddd-a105-4474-a2fe-ab9197a49f17](https://user-images.githubusercontent.com/29353361/206840960-3185710a-f37e-4de7-8b45-ba69f8d92863.png)
[original issue source](https://github.com/viromedia/viro/issues/980)

**Comment by ViktorVojtek** [comment]
Hello, same here. It's happening on Viro React 2.23.0. v 2.22.0 works fine.
Anybody who can take a look at this issue?

**Comment by ViktorVojtek** [comment]
Hello @haidernawaz99 meanwhile this issue would be fixed, use this module. [react-native-view-shot](https://github.com/gre/react-native-view-shot). 
It does exactly what viro scene navigator's takeSchreenshot does and more and it works perfectly fine.

**Comment by ViktorVojtek** [comment]
@haidernawaz99 Hi. Unfortunately you are right. react-native-view-shot works only on iOS. I'm looking for another solution that would work.

**Comment by sjerratsch** [comment]
looks like in version 2.23.0 you have to use the "_takeScreenshot()" function on the ref directly instead of "ref. sceneNavigator.takeScreenshot".

**Comment by skizzo** [comment]
Did somebody manage to take a screenshot using v2.23.0?

**Comment by sarimahmad** [comment]
@skizzo You can take screenshot by using ref and calling the method through ref _takeScreenshot() and don't forgot to pass the ref in the ArsceneNavigator

**Comment by sarimahmad** [comment]
@sjerratsch I am facing the issue in the _startvideorecording , it crash the App when i call this method, Do find any solution for that ?

**Comment by sarimahmad** [comment]
@skizzo  I am getting the same error in _startvideorecording function and I also ended up by using native modules for android and IOS for recording video, I have react-native-view-shot for the picture.

**Comment by andre-sonect** [comment]
@skizzo or @sarimahmad I am trying to use `react-native-view-shot` but with no luck, black screen showing when using it.
`<ViewShot
        ref={viewShotRef}
        handleGLSurfaceViewOnAndroid={true}
        options={{
          fileName: 'ar_photo_' + Date.now(),
          format: 'jpg',
          quality: 0.8,
        }}>
        <ViroARSceneNavigator
          autofocus={true}
          initialScene={{
            scene: RewardScene,
          }}
          style={localStyles.sceneNavigator}
          ref={arNavigator}
          viroAppProps={{
            videoObj: videoObj,
            initialised,
            setInitialised,
            onFinish,
            finished,
            objectType,
          }}
        />
      </ViewShot>`

**Comment by andre-sonect** [comment]
Example to use [react-native-view-shot](https://github.com/gre/react-native-view-shot) with Android:

```
import {captureScreen} from 'react-native-view-shot';

captureScreen({
  format: "jpg",
  quality: 0.8,
  handleGLSurfaceViewOnAndroid: true // <-- add this property here
}).then(
  (uri) => console.log("Image saved to", uri),
  (error) => console.error("Oops, snapshot failed", error)
);
```

**Comment by robertjcolley** [comment]
Can you provide which version of React Native, Mac/Windows, iOS/Android, and Viro? We have a few issues about not being able to take screenshots and I'm trying to collect as much information as possible.

**Comment by andre-sonect** [comment]
> Can you provide which version of React Native, Mac/Windows, iOS/Android, and Viro? We have a few issues about not being able to take screenshots and I'm trying to collect as much information as possible.

Sure,
React-native: 0.67.5
Mac, 
Android 13(OnePlus 8) and 
"@viro-community/react-viro": "2.22.0",

**Comment by andresteves** [comment]
@robertjcolley I know a PR was made but I am still not able to take screenshots on Android 13 with latest Viro version on RN 0.74.0.
