### ISSUE TITLE
Viro ViroARSceneNavigator startVideoRecording, takeScreenshot is not working.

### ISSUE THREAD

**Issue by antiergit** [NativeVision/viro#192]
while using Android 13, I got issue in ViroARSceneNavigator as startVideoRecording and takeScreenShot is returning error code 1. we cannot capture image or record video as library is not compatable with Android 13. 

`  _startRecording() {
    if (!this.state.audioPermission && Platform.OS === 'android') {
      this.requestAudioPermission();
    }

     this._arNavigator._startVideoRecording('teleport_video', true, errorCode => {
      console.log('errorCode ', errorCode);
      this._displayVideoRecordAlert(
        'Recording Error',
        'Please allow video and audio permissions!' + errorCode,
      );
      this.props.dispatchDisplayUIScreen(UIConstants.SHOW_MAIN_SCREEN);
    });
    this.props.dispatchDisplayUIScreen(UIConstants.SHOW_RECORDING_SCREEN);

    this._startStopWatch();
  }`

**Comment by ThomasCarstens** [comment]
Trying with Android 12 with no success. Even though it detects ```res``` it says ```res.status``` and ```res.result.outputURL``` are undefined. Have I made a mistake integrating it?
![image](https://user-images.githubusercontent.com/36089032/214827292-545a5f83-1f9e-4e4d-97a3-e2dbb1fc719b.png)

**Comment by sarimahmad** [comment]
@ThomasCarstens  Still I also facing this issue, do you find any solution

**Comment by alihamzaazhar** [comment]
@ThomasCarstens I am also facing the same issue, any solution?

**Comment by robertjcolley** [comment]
Please fill in the development information in the issue template. We want your projects you build with NativeVision to be successful! However, we are a small team, and we don't have the time to spend trying to figure out what configuration of React Native / iOS / Android / Expo / NativeVision / Windows / MacOS / Linux you are using.

We are also tracking issues like #228 - There is an issue with screenshots and video recording in v2.23.1.

I'll happily reopen with the template filled out! 😊
