### ISSUE TITLE
Help: ViroButton position from yaw and pitch radius

### ISSUE THREAD

**Issue by vlkpa** [NativeVision/viro#20]
Hi guys, in our admin web/browser app for creating static buttons in 360 images (for navigation/tour between 360 images) we use this tool [Pannellum](https://pannellum.org/documentation/examples/hot-spots/)
In mobile app we use React Viro as a view of the tour = 360 images + buttons as links.
In Pannellum buttons/hotspots are positioned in 360 images with **yaw** and **pitch** (in radians).
ViroButton uses for positioning **Cartesian position** as [x,y,z] . 
Is there a way how to convert this yaw and pitch into Cartesian cooridinates?

**Comment by rollingstone** [comment]
Pls use the transformation matrix mentioned here,

https://stackoverflow.com/questions/1568568/how-to-convert-euler-angles-to-directional-vector

**Comment by vlkpa** [comment]
Yes, I saw this answers and tried some solutions but without success.

**Comment by NS-BOBBY-C** [comment]
@vlkpa can you provide more information about the issue you are having? I.E. viro version, maybe a sample repo or some more context as to the issue you are having?

**Comment by robertjcolley** [comment]
Closing due to no update.
