### ISSUE TITLE
Tried to register two views with the same name VRTQuad  react-viro is not compatible with android

### ISSUE THREAD

**Issue by outsource-nz** [NativeVision/viro#202]
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 230.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/muhammadbilal/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages
    *react-native*: Not Found
    
    
    
    
m facing this issue on andorid as well as ios any solution???

Invariant Violation: Tried to register two views with the same name VRTQuad, js engine: hermes
 LOG  Running "SafeSigNZ" with {"rootTag":11}
 ERROR  Invariant Violation: "SafeSigNZ" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

**Comment by spector32** [comment]
This issue is a real show stopper if one is using Expo. This issue has been around for 2 years now, first registered in May 15, 2022. The MR provided is a really good fix and it's just 1 line of code. Why does it takes so long to merge it to master?

**Comment by robertjcolley** [comment]
Closing in favor of #136
