### ISSUE TITLE
Disappearing 3D models in AR depending on camera angle

### ISSUE THREAD

**Issue by dominicwebisoft** [NativeVision/viro#210]
This issue can be closed if you absolutely want to, since I haven't followed the requirements. I just wanted to ask a question that no one seems to be able to answer.

We've been having an issue with our 3D models while being in AR. Depending on the angle of the camera (where you're looking at), the 3D model disappears. If you look back at it, it reappears. 

We've been comparing the demo models with our models and the only thing different is the rigging being in a null layer. Could that really be the cause here? 

We've tried un-animated models and they don't have that disappearing issue, but as soon as we animate them, it bugs.

Or could it all be related to the code in the app itself?

[working_model_without_animation.zip](https://github.com/ViroCommunity/viro/files/11556110/working_model_without_animation.zip)
[disappearing_model_with_animation.zip](https://github.com/ViroCommunity/viro/files/11556111/disappearing_model_with_animation.zip)

Video of working model : 
https://github.com/ViroCommunity/viro/assets/118382553/71be65a0-a64c-4ad8-ab0e-2fa317b6c3c6

Video of disappearing model : 
https://github.com/ViroCommunity/viro/assets/118382553/70d8dce9-a918-41d1-9880-50a59b3b3948

**Comment by tadjik1** [comment]
@dominicwebisoft  hey, how do you use your material with .vrx model? is it included in the bundle or loaded dynamically (using "resources")?
