### ISSUE TITLE
Failed to load complex gltf file

### ISSUE THREAD

**Issue by mmestiyak** [NativeVision/viro#216]
Issue Summary: Complex glTF file with multiple objects not rendering in Viro React app, while simple glTF file with one object works.

Description: We have been working on integrating a 3D model feature into our hardware product's app using three.js and Viro React. However, we are facing an issue where a complex glTF file containing multiple objects fails to render in Viro React. Surprisingly, a simple glTF file with just a circle and a phong mesh renders successfully. We have been troubleshooting this problem for a week without any resolution.

Details:

Viro React supports four material types: basic, phong, lambert, and others.
We are using basic and phong-type objects.
When the glTF file contains a single object, Viro React renders it correctly.
The complex glTF file that doesn't show up in Viro React was created using our tool built on top of three.js. You can find it [here](https://raw.githubusercontent.com/mmestiyak/nothing/main/drone.gltf)
On the other hand, a simple glTF file with one object, also created with three.js, works without any issues. You can find it [here](https://github.com/mmestiyak/nothing/blob/main/PhongMaterial.gltf)
Request: We kindly request assistance in resolving this issue. Any guidance or suggestions would be greatly appreciated. Thank you for your help!

**Comment by robertjcolley** [comment]
Please fill in the development information in the issue template. We want your projects you build with NativeVision to be successful! However, we are a small team, and we don't have the time to spend trying to figure out what configuration of React Native / iOS / Android / Expo / NativeVision / Windows / MacOS / Linux you are using.

I'll happily reopen with the template filled out! 😊
