### ISSUE TITLE
 Viro360Image always rolls on iOS

### ISSUE THREAD

**Issue by Turtleted21** [NativeVision/viro#223]
Hello
I try to use Viro360Image but image constantly rolls on iOS.
Tested on iPhoneXR, iPad pro and iPad mini.
It work on Android.

video example :

https://github.com/ViroCommunity/viro/assets/46889785/ff6ee523-d2da-4691-83f0-738d6dc3390c

Thanks

**Comment by robertjcolley** [comment]
Please fill in the development information in the issue template. We want your projects you build with NativeVision to be successful! However, we are a small team, and we don't have the time to spend trying to figure out what configuration of React Native / iOS / Android / Expo / NativeVision / Windows / MacOS / Linux you are using.

I'll happily reopen with the template filled out! 😊
