### ISSUE TITLE
Cannot read property 'isARSupportedOnDevice' of null on RN version 0.72.6 in android device

### ISSUE THREAD

**Issue by ankittrootech123** [NativeVision/viro#233]
## Description
I tried to run this library on RN version 0.72.6 and faced this issue in android devices but working on ios device. can you please help with the solution?

![Screenshot 2023-10-30 at 1 07 19 PM](https://github.com/ViroCommunity/viro/assets/145343706/4d92a474-51c7-4547-9379-23a756fb24ed)

also i downgraded the react native version to 0.71.3 but still getting this type of error.. please guide me how can I solve this issue

**Comment by hadnet** [comment]
@ankittrootech123 sorry bother you, but did you resolve this issue?

**Comment by ankittrootech123** [comment]
No, not yet.
*Thanks & regards,*

*Ankit Limbad*
*React-Native Developer*
*TRooTech Business Solutions Pvt. Ltd.*

*https://www.trootech.com* <https://www.trootech.com/>

**Comment by Wildanzr** [comment]
it seems okay on RN: **0.72.6** with viro: **^2.40.1**
Make sure to import it correctly
`import { isARSupportedOnDevice } from "@viro-community/react-viro";`

As per [Viro docs (IsARSupportedOnDevice)](https://viro-community.readme.io/docs/isarsupportedondevice) the example code snippet should be updated.
