### ISSUE TITLE
is it possible to combine RNcamera with viro-community/react-viro

### ISSUE THREAD

**Issue by narayanan8uplogic** [NativeVision/viro#246]
<RNCamera
          ref={cameraRef}
          style={{flex: 1}}
          type={RNCamera.Constants.Type.back}
          onFaceDetectionError={error => console.log(error, 'error')}
          onFacesDetected={faces => {
            handleFaceDetection(faces);
          }}
          faceDetectionLandmarks={
            RNCamera.Constants.FaceDetection.Landmarks.all
          }
          faceDetectionMode={RNCamera.Constants.FaceDetection.Mode.accurate}
          autoFocus={RNCamera.Constants.AutoFocus.on}
          autoFocusPointOfInterest={{x: 0.5, y: 0.5}}>
          <Text style={{color: 'white', textAlign: 'center'}}>
            Face detection
          </Text>
          <ViroARSceneNavigator
            initialScene={{scene: renderARScene}}
            style={{flex: 1}}
          />
        </RNCamera>
        
        
i have tried to use like above ,it results in camera conflict when both packages tries to access camera 

## Environment

Linux
@viro-community/react-viro": "^2.23.0
react-native": "^0.71.1"

**Comment by robertjcolley** [comment]
Hi @narayanan8uplogic, currently it is not possible to use anything other than the camera provided by NativeVision. We have put it on the roadmap!

**Comment by narayanan8uplogic** [comment]
Hi @robertjcolley , I want to use the face detection option, and after detecting a face, I want to show objects on different parts of the face. Is that possible with ViroCommunity/React-Viro?

**Comment by robertjcolley** [comment]
Currently, it is not. We are planning on getting to this soon, as it is highly requested.
