### ISSUE TITLE
Which starter kit to use?

### ISSUE THREAD

**Issue by victorbstan** [NativeVision/viro#252]
There seems to be two starter kit repos, one was last updated 2 days ago (https://github.com/NativeVision/expo-viro-starter-kit), and another was updated 2 years ago (https://github.com/NativeVision/starter-kit). 

The viro documentation and github profile link to the old 2 year project. Which one is the correct starter kit we are supposed to use?

**Comment by cjmcassar** [comment]
Hi! The expo started kit is updated with the most recent version of viro react. The older starter kit hasn't been updated yet. Apologies about this we're still in the process of cleaning the repo up

**Comment by robertjcolley** [comment]
I've verified the starter kits with iOS, but not with Android. Help is wanted - if you can verify with android or help with Android

Starter kits to use:
- [Expo + TypeScript](https://github.com/NativeVision/expo-starter-kit-typescript)
- [React Native](https://github.com/NativeVision/starter-kit)
- [Expo + JavaScript](https://github.com/NativeVision/expo-starter-kit)
