### ISSUE TITLE
Android 13 not able to take screenshot

### ISSUE THREAD

**Issue by andre-sonect** [NativeVision/viro#254]
# Requirements:

Please go through this checklist before opening a new issue

- [X] Review the [documentation](https://docs.viromedia.com/)
- [X] Search for existing issues in: [viromedia/viro](https://github.com/viromedia/viro/issues) & [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
- [X] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment

Please provide the following information about your environment:

1. Development OS: Mac
2. Device OS & Version: Android OS version (13) or iOS version (17)
3. Version: ViroReact 2.3.0 and React Native 0.67.5
4. Device(s): OnePlus 8

## Description

When using `_takeScreenshot` on Android it will always fail while working fine on iOS. I suspect it has something to do with the storage permissions but can't really pinpoint to that since I get as a response not success and errorCode 1.

## Reproducible Demo

```
if (arNavigator.current) {
        var timestamp = Date.now();
        arNavigator.current
          ._takeScreenshot('ar_photo_' + timestamp, true)
          .then(retDict => {
            if (!retDict.success) {
              if (retDict.errorCode === 1) {
                if (Platform.OS === 'ios') {
                  setPhotoLibraryPermissionError(true);
                }
                return;
              }
            }
            navigation.push('PhotoProcess', {
              uri: 'file://' + retDict.url,
              videoObj,
            });
          })
          .catch(error => {
            console.log(error);
          });
      }
```

**Comment by robertjcolley** [comment]
Reproduced on iOS as well. https://github.com/NativeVision/viro/assets/29097404/0680f472-65f0-475b-9a1e-a75fd55d9f93
