### ISSUE TITLE
Fix android building with Java 17, Kotlin, and Expo

### ISSUE THREAD

**Issue by robertjcolley** [NativeVision/viro#260]
Issue here to track issues with Android on newer versions of React Native, Expo 50 Kotlin issues, and more related to Android.

**Comment by Avtrkrb** [comment]
@robertjcolley I have an idea for upgrading arcore version. I'm trying it out in my free time. Will create a pr if I have successful results.

**Comment by Avtrkrb** [comment]
@robertjcolley @cjmcassar @bobbyjcolley 
I've raised a few draft PRs to [vircore](https://github.com/NativeVision/virocore/pull/137) & [viro](https://github.com/NativeVision/viro/pull/263) that should fix a lot of issues for android. It's still WIP though, will tag you once it's ready.
