### ISSUE TITLE
Touch an element with viro react

### ISSUE THREAD

**Issue by lvothnrv** [NativeVision/viro#278]
Hello friends, I needed some clarification, can you touch with your finger directly with the camera an element that you are displaying, for example a text. Because I tried to do an onTouch and an onClick nothing happens. Knowing that onClick crashes my application.

**Comment by robertjcolley** [comment]
Hi! Please fill in the development information in the issue template. We want your projects you build with NativeVision to be successful! However, we are a small team, and we don't have the time to spend trying to figure out what configuration of React Native / iOS / Android / Expo / NativeVision / Windows / MacOS / Linux you are using.

I'll happily reopen with the template filled out! 😊
