### ISSUE TITLE
build issue iOS, libViroReact.a[arm64][2](VRTPortalScene.o))

### ISSUE THREAD

**Issue by yauhenicharniauski** [NativeVision/viro#279]
# Requirements: 

Please go through this checklist before opening a new issue
  - [X] Review the [documentation](https://viro-community.readme.io/docs/overview)
  - [X] Search for existing issues in: [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [X] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment

Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: MacBook Pro M1 
3. Version: ViroReact: 2.41.1, ReactNative: 0.73.5 

## Description

After Installation Instructions via StartKit or manually installing and linking the library to an existing React Native project, I have this issue after building the project.

```
ld: building for 'iOS-simulator', but linking in object file (/Users/yauheni/iTechArt/starter-kit/node_modules/@viro-community/react-viro/ios/dist/lib/libViroReact.a[arm64][2](VRTPortalScene.o)) built for 'iOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried to exclude arm64 arch, but after that I received issue:

`Library 'CocoaAsyncSocket' not found`

## Reproducible Demo

1) StartKit
2) npm install
3) cd ios && pod install && cd ..
4) npm start, iOS

**Comment by steve-glen** [comment]
@yauhenicharniauski Hi, Same Issue. Did you resolve this issue, and if so, how did you do it?
React Native 0.73.9
Viro 2.41.6

**Comment by canceryoon** [comment]
@yauhenicharniauski Hi, Same Issue. Did you resolve this issue, and if so, how did you do it?
MacBook Pro M1
React Native 0.73.9
Viro 2.41.6

**Comment by Redn4s** [comment]
@yauhenicharniauski Same issue here. How did you resolve the issue?
